name: lamdu-calculus
version: 0.2.0.1
github: "lamdu/lamdu-calculus"
license: BSD3
author: "Yair Chuchem, Eyal Lotem"
maintainer: "yairchu@gmail.com"
copyright: "2021 Yair Chuchem, Eyal Lotem"

extra-source-files:
- README.md

synopsis: The Lamdu Calculus programming language
category: Language

description: Please see README.md

dependencies:
- base >= 4.7
- base-compat >= 0.8.2
- bytestring
- containers
- hypertypes >= 0.2
- lens >= 4.1

ghc-options:
- -fexpose-all-unfoldings
- -Wall
- -Wnoncanonical-monad-instances
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wunused-packages
- -fdicts-cheap
- -O2
- -fspecialise-aggressively

ghc-prof-options:
- -O2

library:
  source-dirs: src
  other-modules:
  - Lamdu.Calc.Internal.Prelude
  dependencies:
  - base16-bytestring
  - binary
  - deepseq
  - generic-constraints
  - generic-data
  - hashable
  - lattices
  - monad-st
  - mtl
  - pretty >= 1.1.2
  - transformers

tests:
  lamdu-calculus-test:
    main: test.hs
    source-dirs: test
    dependencies:
    - HUnit
    - lamdu-calculus
    - test-framework
    - test-framework-hunit

benchmarks:
  lamdu-calculus-bench:
    main: benchmark.hs
    source-dirs: test
    ghc-options:
    - -O2
    - -Wall
    - -Wnoncanonical-monad-instances
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - criterion
    - deepseq
    - monad-st
    - mtl
    - lamdu-calculus
    - transformers
